language: go

notifications:
  email: false

env:
  global:
    - secure: "CPu3y63Gx4OsC05IpgwIBOfpZw/kgsPKwnDNllRpHN+GRVyyObHBoDUV3HbDzmyRZfCKemD+pqNBU4eqtxEvkePGEH40axpWrVdegV2Yb+fc1ZfT310pUVSMQA2BORAtRNan/Hz0AphXj2Fib8DFmoRTD8gIu/35hOeQqYlZAR8="
    - PATH=$HOME/gopath/bin:$PATH

# TODO(u): Update import path of vet and cover when Travis starts using Go 1.4.

before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get code.google.com/p/go.tools/cmd/vet
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get github.com/mewmew/gobase/...

before_script:
  - wget https://gist.githubusercontent.com/mewmew/379014c9a2e6885e238d/raw/fb0c7d164113b1428f886dd470a613c74b9a9997/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
